modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/Ladysnake/Illuminations-for-Forge/issues" #optional

logoFile="illuminations.png" #optional

[[mods]] #mandatory

modId="illuminations" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Illuminations for Forge" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/illuminations-for-forge" #optional

credits="AbsolemJackdaw & Subaraki, for porting the mod to Forge" #optional
authors="The Ladysnake community, and Doctor4t for making the mod" #optional
description='''
Illuminations (originally coded with Fabric Mod loader) adds in ambient fireflies that spawn in the night on grass patches where they reside.
'''

[[dependencies.illuminations]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
	
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
